#############################################################################
# Platform Features Configuration
#
# Default settings for all environments
# 
# You can overload any feature for any environment by changing the 
# environment settings at the bottom of the file
#############################################################################

defaults: &defaults
  enabled_features: [dashboard, apps, forum, help]
  
  dashboard:
    title:            Dashboard
    link:             /platform/developer/dashboard
    controller:       dashboard
    actions:          [index]
    manager_only:     false
  
  apps:
    title:            Applications
    link:             /platform/developer/apps
    controller:       apps
    actions:          [index, view]
    manager_only:     false

  forum:
    title:            Discussions
    link:             /platform/developer/forum
    controller:       forum
    actions:          [index, topic, message]
    manager_only:     false
  
  help:
    title:            Help
    link:             /platform/developer/help
    controller:       help
    actions:          []
    manager_only:     false

  test:
    title:            Test
    link:             http://www.google.com
    controller:       test
    actions:          [index]
    manager_only:     false
    
    
#############################################################################
# Environment Settings
# You can overload any feature defined in the defaults for any environment
#############################################################################
development:
  <<: *defaults

test:
  <<: *defaults
      
qa:
  <<: *defaults

stage:
  <<: *defaults

production:
  <<: *defaults
