comment:
  title: "Comment Structure"
  type: "struct"
  description: "Returns comment elements."
  fields:
    title: 
      description: "Comment title"
      type: "String"
    comment: 
      description: "Comment text"
      type: "String"
    created_at:  
      description: "Comment's creation date as a timestamp"
      type: "String"
