date:
  title: "Date Structure"
  type: "struct"
  description: "Returns date elements."
  fields:
    day: 
      description: "Date's day"
      type: "Number"
    month: 
      description: "Date's month"
      type: "Number"
    year: 
      description: "Date's year"
      type: "Number"
    circa:  
      description: "Indicates wether the date is an approximation"
      type: "Boolean"
