video:
  type: "api"
  path: "video"
  sample: "https://www.geni.com/api/video-21557506"
  description: "Returns information about a video."
  status: updated
  
  params:
    ids: 
      type: "Array"
      array_type: "String"
      description: "You can select a group of videos on specific urls. For example: https://www.geni.com/api/video?ids=101,31534,145 returns video data for all three ids."
      required: false
    fields:
      type: "Array"
      array_type: "String"
      description: "You can pass a list of fields you want returned in your call. For example, to get just the title of a video: https://www.geni.com/api/video-21557506?fields=title."
      required: false

  fields:
    id: 
      description: "The video's id"
      type: "String"
      public: true
    title: 
      description: "The video's title"
      type: "String"
      public: true
    url: 
      description: "The api url of the video"
      type: "String"
      public: true
    date: 
      description: "The video's date"
      type: "Date"
      public: true
    content_type:
      description: "The video's original content type"
      type: "String"
      public: true
    sizes:
      description: "URLs to the video's sizes"
      type: "VideoImageSizeMap"
      public: true
    guid: 
      description: "The old GUID"
      type: "String"
      public: true
    created_at: 
      description: "Timestamp of when the video was created"
      type: "String"
    updated_at: 
      description: "Timestamp of when the video was last updated"
      type: "String"
    location: 
      description: "The video's location"
      type: "Location"
      status: added

  param_groups:
    pagination_params:
      count: 
        type: "Boolean"
        description: "Only return the count: true or false (default false)"
        required: false
      page: 
        type: "Number"
        description: "Page number of results to return. Default 1."
        required: false
      per_page: 
        type: "Number"
        description: "Number of results per page. Max 50 (default 50)"
        required: false
      fields:
        type: "Array"
        array_type: "String"
        description: "You can pass a list of fields you want returned in your call."
        required: false
    update_fields: [title, description, date]
    
  actions:
    add:
      path: "video/add" 
      method: POST
      status: added
      description: "Uploads and creates a video."
      sample: "https://www.geni.com/api/video/add?title=foo&text=text-doc"
      params:
        title: 
          description: "The video's title"
          type: "String"
          required: true
        description: 
          description: "The video's description"
          type: "String"
          required: false
        date: 
          description: "The video's date in JSON form"
          type: "Date"
          required: false
        file:
          description: "File to create video from"
          type: "Binary"
          required: false
      fields: *
  
    tag: 
      path: "video/tag" 
      method: POST
      description: "Tags a person in a video."
      sample: "https://www.geni.com/api/video-1/tag/profile-1"
      fields: *
      
    untag: 
      path: "video/untag" 
      method: POST
      description: "Removes a person tag from a video."
      sample: "https://www.geni.com/api/video-1/untag/profile-1"
      fields: *

    tags: 
      path: "video/tags" 
      method: GET
      description: "Returns a list of people tagged in a video."
      sample: "https://www.geni.com/api/video-339953/tags"
      params: pagination_params
      fields:
        results:
          description: "The list of profiles tagged in a video"
          type: "Array"
          array_type: "Profile"
        prev_page:
          description: "Link to the previous page of results (if any)"
          type: "String"
        next_page:
          description: "Link to the next page of results (if any)"
          type: "String"
        page:
          description: "Page number"
          type: "Number"
          
    update:
      path: "video/update" 
      method: POST
      status: added
      description: "Updates video data and returns the updated video."
      sample: "https://www.geni.com/api/video-1/update?title=foo"
      params: update_fields
      fields: *

    delete:
      path: "video/delete" 
      method: POST
      status: added
      description: "Deletes video."
      sample: "https://www.geni.com/api/video-1/delete"      
      
    comments: 
      path: "video/comments"
      status: added 
      method: GET
      description: "Returns a list of video comments"
      sample: "https://www.geni.com/api/video-1/comments"
      params: pagination_params
      fields:
        results:
          description: "The list of video comments"
          type: "Array"
          array_type: "Comment"
        prev_page:
          description: "Link to the previous page of results (if any)"
          type: "String"
        next_page:
          description: "Link to the next page of results (if any)"
          type: "String"
        page:
          description: "Page number"
          type: "Number"

    comment: 
      path: "video/comment"
      status: added 
      method: POST
      description: "Adds a comment to the video"
      sample: "https://www.geni.com/api/video-1/comment"
      params: 
        title: 
          description: "Comment title"
          type: "String"
          required: false
        text: 
          description: "Comment text"
          type: "String"
          required: true
      fields:
        results:
          description: "The list of video comments"
          type: "Array"
          array_type: "Comment"
        prev_page:
          description: "Link to the previous page of results (if any)"
          type: "String"
        next_page:
          description: "Link to the next page of results (if any)"
          type: "String"
        page:
          description: "Page number"
          type: "Number"
           