document_image_size_map:
  title: "Document Image Size Map Structure"
  type: "struct"
  description: "Urls of the document image sizes."
  fields:
    large: 
      description: "URL of the large image"
      type: "String"
      public: true
    origin: 
      description: "URL of the original image"
      type: "String"
      public: true
    thumb: 
      description: "URL of the thumb image"
      type: "String"
      public: true
