profile:
  type: "api"
  path: "profile"
  sample: "https://www.geni.com/api/profile-101"
  description: "Returns information about a profile."
  status: changed
  
  params:
    ids:
      type: "Array"
      array_type: "String"
      description: "You can select a group of profiles on specific urls. For example: https://www.geni.com/api/profile?ids=101,31534,145 returns profile data for all three ids."
      required: false
    fields:
      type: "Array"
      array_type: "String"
      description: "You can pass a list of fields you want returned in your call. For example, to get just the first and last names of a profile: https://www.geni.com/api/profile-21557506?fields=first_name,last_name."
      required: false
    only_ids:
      type: "Boolean"
      description: "The returned data structures will contain urls to other objects in our system unless the request includes 'only_ids=true.' Passing only_ids will force the system to return ids only."
      required: false
      
  fields:
    id:
      description: "The profile's node id"
      type: "String"
    url:
      description: "URL to access profile"
      type: "String"
    public:
      description: "True if the profile is public"
      type: "Boolean"
      status: deprecated
    guid:
      description: "Old profile guid"
      type: "String"
    first_name:
      description: "The profile's first name"
      type: "String"
    middle_name:
      description: "The profile's middle name"
      type: "String"
    maiden_name:
      description: "The profile's maiden name"
      type: "String"
    last_name:
      description: "The profile's last name"
      type: "String"
    suffix:
      description: "The profile's suffix"
      type: "String"
    display_name:
      description: "The profile's display name"
      type: "String"
    name:
      description: "The profile's name as it appears on the site to the current user"
      type: "String"
    is_alive:
      description: "True if the profile is alive"
      type: "Boolean"
    gender:
      description: "The profile's gender: f, m or u"
      type: "String"
    current_residence:
      description: "The profile's current address"
      type: "String"
      status: changed
    current_residence_parts:
      description: "The profile's current address"
      type: "Location"
      status: deprecated
    occupation:
      description: "Profile's occupation"
      type: "String"
    created_by:
      description: "The url (or id) of the profile who added this profile to the tree"
      type: "String"
      status: deprecated
    managers:
      description: "Urls (or ids) of profile(s) currently managing this profile"
      type: "Array or String"
      status: changed
    merged_into:
      description: "The urls (or ids) of the profile(s) this profile is currently merged into"
      type: "Array or String"
      status: changed
    requested_merges:
      description: "The urls (or ids) of the profile(s) requested to be merged into this one"
      type: "Array or String"
      status: changed
    merge_note:
      description: "Note explaining the profile's merge status"
      type: "String"
    big_tree:
      description: "True if the profile is attached to the big tree"
      type: "Boolean"
      status: deprecated
    claimed:
      description: "True if the profile is claimed by a user"
      type: "Boolean"
      status: deprecated
    locked:
      description: "True if the profile has been locked down by a curator"
      type: "Boolean"
      status: deprecated
    birth_date:
      description: "Profile's birth date"
      type: "String"
      status: deprecated
    birth_date_parts:
      description: "Profile's birth date in parts"
      type: "Date"
      public: false
      status: deprecated
    birth_location:
      description: "Profile's birth location"
      type: "String"
      public: false
      status: deprecated
    baptism_date:
      description: "Profile's baptism date"
      type: "String"
      public: false
      status: deprecated
    baptism_date_parts:
      description: "Profile's baptism date in parts"
      type: "Date"
      public: false
      status: deprecated
    baptism_location:
      description: "Profile's baptism location"
      type: "String"
      public: false
      status: deprecated
    death_date:
      description: "Profile's death date"
      type: "String"
      status: deprecated
    death_date_parts:
      description: "Profile's death date in parts"
      type: "Date"
      status: deprecated
    death_location:
      description: "Profile's death location"
      type: "String"
      status: deprecated
    burial_date:
      description: "Profile's burial date"
      type: "String"
      status: deprecated
    burial_date_parts:
      description: "Profile's burial date in parts"
      type: "Date"
      status: deprecated
    burial_location:
      description: "Profile's burial location"
      type: "String"
      status: deprecated
    about_me:
      description: "Profile's 'about me' section"
      type: "String"
    language:
      description: "Profile's language"
      type: "String"
    curator:
      description: "Profile's curator's url (or id)"
      type: "String"
    mugshot_urls:
      description: "All sizes of the profile's main photo"
      type: "PhotoImageSizeMap"
    unions:
      description: "Profile's unions as urls (or ids)"
      type: "Array or String"
    relationship:
      description: "Profile's relationship to the current user"
      type: "String"
    email:
      description: "Profile's email"
      type: "String"
    phone_numbers:
      description: "Profile's phone numbers"
      type: "Array"
      array_type: "String"
    get_email:
      description: "Indicates whether the profile can receive email"
      type: "Boolean"
    merge_pending:
      description: "Indicates whether the profile has a pending merge"
      type: "Boolean"
    block_exists:
      description: "Indicates whether the profile is blocked"
      type: "Boolean"
    master_profile:
      description: "Indicates whether the profile is a master profile"
      type: "Boolean"
    premium_start_date:
      description: "Date when the profile became a pro user"
      type: "String"

  field_groups:
    all:          [about_me, baptism_date, baptism_date_parts, baptism_location, baptism_location_parts, big_tree, birth_date, birth_date_parts, birth_location, birth_location_parts, burial_date, burial_date_parts, burial_location, burial_location_parts, claimed, created_by, curator, current_residence, death_date, death_date_parts, death_location, death_location_parts, display_name, email, first_name, gender, guid, id, is_alive, language, last_name, locked, maiden_name, managers, merge_note, merged_into, middle_name, mugshot_urls, name, occupation, phone_numbers, public, relationship, requested_merges, suffix, unions, url]
    detail:       [baptism_date, baptism_date_parts, baptism_location, baptism_location_parts, big_tree, birth_date, birth_date_parts, birth_location, birth_location_parts, burial_date, burial_date_parts, burial_location, burial_location_parts, claimed, created_by, curator, current_residence, death_date, death_date_parts, death_location, death_location_parts, display_name, email, first_name, gender, guid, id, is_alive, language, last_name, locked, maiden_name, managers, merge_note, merged_into, middle_name, mugshot_urls, name, occupation, phone_numbers, public, relationship, requested_merges, suffix, unions, url]
    focus:        [id, guid, url, first_name, last_name, suffix, name, gender, is_alive, public, locked, claimed, big_tree, birth_date, birth_location, current_residence, creator]
    list:         [id, url, public, locked, name, first_name, middle_name, last_name, suffix, display_name, gender, is_alive, birth_date, birth_location, baptism_date, baptism_location, death_date, death_location, burial_date, burial_location]
    merge:        [id, url, first_name, middle_name, last_name, maiden_name, name, gender, is_alive, birth_date, death_date]
    visible_tree: [block_exists, claimed, display_name, editable, email, first_name, get_email, guid, id, is_alive, last_name, locked, maiden_name, master_profile, merge_pending, middle_name, mugshot_urls, name, premium_start_date, public, suffix]
    walk:         [first_name, gender, id, is_alive, last_name, public, url]

  field_groups:
    all:          [about_me, baptism_date, baptism_date_parts, baptism_location, baptism_location_parts, big_tree, birth_date, birth_date_parts, birth_location, birth_location_parts, burial_date, burial_date_parts, burial_location, burial_location_parts, claimed, created_by, curator, current_residence, death_date, death_date_parts, death_location, death_location_parts, display_name, email, first_name, gender, guid, id, is_alive, language, last_name, locked, maiden_name, managers, merge_note, merged_into, middle_name, mugshot_urls, name, occupation, phone_numbers, public, relationship, requested_merges, suffix, unions, url]
    detail:       [baptism_date, baptism_date_parts, baptism_location, baptism_location_parts, big_tree, birth_date, birth_date_parts, birth_location, birth_location_parts, burial_date, burial_date_parts, burial_location, burial_location_parts, claimed, created_by, curator, current_residence, death_date, death_date_parts, death_location, death_location_parts, display_name, email, first_name, gender, guid, id, is_alive, language, last_name, locked, maiden_name, managers, merge_note, merged_into, middle_name, mugshot_urls, name, occupation, phone_numbers, public, relationship, requested_merges, suffix, unions, url]
    focus:        [id, guid, url, first_name, last_name, suffix, name, gender, is_alive, public, locked, claimed, big_tree, birth_date, birth_location, current_residence, creator]
    list:         [id, url, public, locked, name, first_name, middle_name, last_name, suffix, display_name, gender, is_alive, birth_date, birth_location, baptism_date, baptism_location, death_date, death_location, burial_date, burial_location]
    merge:        [id, url, first_name, middle_name, last_name, maiden_name, name, gender, is_alive, birth_date, death_date]
    visible_tree: [block_exists, claimed, display_name, editable, email, first_name, get_email, guid, id, is_alive, last_name, locked, maiden_name, master_profile, merge_pending, middle_name, mugshot_urls, name, premium_start_date, public, suffix]
    walk:         [first_name, gender, id, is_alive, last_name, public, url]

  actions:
    data-conflicts:
      path: "profile/data-conflicts"
      method: GET
      description: "Returns a list of data conflicts for the current user."
      sample: "https://www.geni.com/api/profile/data-conflicts"
      params:
        collaborators:
          type: "Boolean"
          description: "Will also return the data conflicts for the current user’s collaborators"
          required: false
      fields:
        results:
          description: "The list of data conflics"
          type: "Array"
          array_type: "DataConflict"

    documents:
      path: "profile/documents"
      method: GET
      description: "Returns a list of documents tagged with a profile."
      sample: "https://www.geni.com/api/profile/documents"
      fields:
        results:
          description: "The list of documents tagged with a profile"
          type: "Array"
          array_type: "Document"

    immediate-family:
      path: "profile/immediate-family"
      method: GET
      description: "Returns a list of documents tagged with a profile. Tamura Jones wrote an <a href='http://www.tamurajones.net/TheGeniModel.xhtml'>excellent summary</a> of our immediate family data."
      sample: "https://www.geni.com/api/profile/immediate-family"
      fields:
        focus:
          description: "The focus profile whose immediate family is being retreived"
          type: "Profile"

        nodes:
          description: "Hash of unions and profiles for the immediate family"
          type: "Hash"

    merge:
      path: "profile/merge"
      method: POST
      description: "Will merge two profiles together if you have permission, or it will create a requested merge if you don’t have edit permission on both profiles."
      sample: "https://www.geni.com/api/profile-1/merge/profile-2"
    merges:
      path: "profile/merges"
      method: GET
      description: "Will merge two profiles together if you have permission, or it will create a requested merge if you don’t have edit permission on both profiles."
      sample: "https://www.geni.com/api/profile-1/merge/profile-2"
      params:
        collaborators:
          type: "Boolean"
          description: "Will also return the merges for the current user’s collaborators"
          required: false
      fields:
        results:
          description: "The list of requested profile merges for the current user"
          type: "Array"
          array_type: "ProfileMergeRequest"

    photos:
      path: "profile/photos"
      method: GET
      description: "Returns a list of photos tagged with a profile."
      sample: "https://www.geni.com/api/profile/photos"
      fields:
        results:
          description: "The list of photos tagged with a profile"
          type: "Array"
          array_type: "Photo"

    videos:
      path: "profile/videos"
      method: GET
      description: "Returns a list of videos tagged with a profile."
      sample: "https://www.geni.com/api/profile/videos"
      fields:
        results:
          description: "The list of videos tagged with a profile"
          type: "Array"
          array_type: "Video"

    search:
      path: "profile/search"
      method: GET
      description: "Returns a list of photos tagged with a profile."
      sample: "https://www.geni.com/api/profile/photos"
      params:
        names:
          type: "String"
          description: "The names you wish to search for."
          required: false
      fields:
        results:
          description: "The list of profiles found in the search"
          type: "Array"
          array_type: "Profile"

    tree-conflicts:
      path: "profile/tree-conflicts"
      method: GET
      description: "Returns a list of tree conflicts for the current user."
      sample: "https://www.geni.com/api/profile/tree-conflicts"
      params:
        collaborators:
          type: "Boolean"
          description: "Will also return the tree conflicts for the current user’s collaborators"
          required: false
      fields:
        results:
          description: "The list of tree conflics"
          type: "Array"
          array_type: "TreeConflict"

    tree-matches:
      path: "profile/tree-matches"
      method: GET
      description: "Returns a list of other profiles in our system matching a given profile. Only users who have upgraded to a Geni Pro Account can see this list."
      sample: "https://www.geni.com/api/profile/tree-matches"
      fields:
        results:
          description: "The list of profile matches"
          type: "Array"
          array_type: "Profile"


